config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "users#index"
  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :new, :create, :destroy] do
      resources :comments, only: [:new, :create, :destroy]
      resources :likes, only: [:new, :create]
    end
  end
  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :posts, only: [:index] do
        resources :comments, only: [:index, :create]
      end
    end
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  has_many :likes, class_name: 'Like', dependent: :destroy
  has_many :comments, dependent: :destroy

  after_save :update_post_counter

  def recent_comments
    Comment.order(created_at: :desc).limit(5)
  end

  def update_post_counter
    author.increment!(:post_counter)
  end
end

app/controllers/api/v1/posts_controller.rb
module Api
  module V1
    class PostsController < ApiController
      before_action :authorize_request

      def list_posts
        author_id = params[:user_id]
        if author_id
          posts = Post.where(author_id:)
          render json: { status: 'SUCCESS', message: 'Loaded posts successfully', data: posts }, status: :ok
        else
          render json: { status: 'ERROR', message: 'User posts not found' }, status: :not_found
        end
      end

      def list_comments
        author_id = params[:user_id]
        post_id = params[:post_id]
        if author_id && post_id
          comments = Comment.where(author_id:, post_id:)
          render json: { status: 'SUCCESS', message: 'Loaded comments successfully', data: comments },
                 status: :ok
        else
          render json: { status: 'ERROR', message: 'User or post not found' }, status: :not_found
        end
      end

      def add_comment
        author_id = @current_user.id
        text = params[:text]
        post_id = params[:post_id]
        if author_id && text && post_id
          comment = Comment.new(author_id:, text:, post_id:)
          if comment.save
            render json: { status: 'SUCCESS', message: 'Saved comment successfully', data: comment },
                   status: :ok
          else
            render json: { status: 'ERROR', message: 'Comment not saved', data: comment.errors },
                   status: :unprocessable_entity
          end
        else
          render json: { status: 'ERROR', message: 'Parameters incomplete' }, status: :not_found
        end
      end
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: %i[create destroy]
  load_and_authorize_resource
  def index
    @user = User.find(params[:user_id])
    @posts = @user.posts.includes(:comments)
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @author = User.find(params[:user_id])
    @post = @author.posts.new(post_params)

    if @post.save
      redirect_to user_path(id: @post.author_id), notice: 'Post was successfully created'

    else
      render :new, alert: 'Error ccurred while creating the post'
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @author = @post.author
    @author.decrement!(:post_counter)
    @post.destroy!
    redirect_to user_posts_path(id: @author.id), notice: 'Post was deleted successfully!'
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/views/posts/index.html.erb
<h1>List of all posts for <%= @user.name %></h1>

<section>
  <div class="card flex">
    <div class="user-image border">
      <%= image_tag('R.png',  :width => "100px", :heigth=>"100px") %>
    </div>
    <div class="user-data border">
      <h1><%= @user.name %></h1>
      <p class="number-posts">Number of posts: <%= @user.post_counter %></p>
      <div class="right">
        <%= link_to "See all users", users_path, class: "btn" %>
        <%= link_to "Add a post",new_user_post_path(@user), class: "btn right" %>
      </div>
    </div>
  </div>
</section>
<section>
  <ul>
    <% @posts.each do |post| %>
      <%= link_to user_post_path(user_id: post.author_id, id: post.id) do %>
        <li class="card left">
          <div class="card">
            <h2><%= post.title %></h2>
            <p><%= post.text %></p>
            <div class="right">
              <span>Comments: <%= post.comments_counter %></span>
              <span>Likes: <%= post.likes_counter %> </span>
            </div>
          </div>
          <div class="commets-container">
            <h4>Comments:</h4>
            <ul>
              <% post.recent_comments.each do |comment| %>
                <p><%= comment.author.name %>: <%= comment.text %></p>
              <% end %>
            </ul>
          </div>
        </li>
      <% end %>
    <% end %>
  </ul>
</section>

app/views/posts/new.html.erb
<section>
  <h1 class="users-title">Add a new post</h1>
  <%= form_with model: @post, url: user_posts_path, class: "card left" do |form| %>
    <%= form.label :title %> <br>
    <%= form.text_field :title %> <br>
    <%= form.label :text %> <br>
    <%= form.text_area :text , cols: 30, rows: 10 %> <br>
    <%= form.submit "Submit", class: "btn" %>
  <% end %>
</section>

app/views/posts/show.html.erb
<h1>Welcome to post show page</h1>

<section class="card left">

  <div class="card">
    <h2><%= @post.title %></h2>
    <p><%= @post.text %></p>
    <div class="right">
      <span>Comments: <%= @post.comments_counter %></span>
      <span>Likes: <%= @post.likes_counter %> </span>
    </div>
    <div class="right my-1 flex justify-end">
      <% if user_signed_in? %>
        <%= link_to "Add comment", new_user_post_comment_path(user_id: @post.author_id, post_id: @post.id ), class: "btn" %>
        <%= form_with model: @like, url: user_post_likes_path(post_id: @post.id) do |form| %>
          <%= form.submit "Add Like", class: "btn" %>
        <% end %>
        <% if can? :destroy, @post %>
          <%= button_to "Delete post", user_post_path(user_id: @post.author.id, post_id: @post.id), method: :delete, class: 'btn-del'  %>
        <% end %>
      <% end %>
    </div>
  </div>

  <div class="commets-container">
    <h4>Comments:</h4>
    <ul>
          <% @post.comments.includes(:author).includes(:post).each do |comment| %>
        <li class="flex justify-between align-center">
          <p class="p-1"><%= comment.author.name %>: <%= comment.text %></p>
          <% if can? :destroy, comment %>
            <%= button_to "Delete comment", user_post_comment_path(user_id: comment.author.id, post_id: comment.post.id, id: comment.id), method: :delete, class: 'btn-del'  %>
          <% end %>
        </li>
        <% end %>
</section>