config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "users#index"
  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :new, :create, :destroy] do
      resources :comments, only: [:new, :create, :destroy]
      resources :likes, only: [:new, :create]
    end
  end
  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :posts, only: [:index] do
        resources :comments, only: [:index, :create]
      end
    end
  end
end

app/views/layouts/_navbar.html.erb
<nav>
    <div class="container nav">
      <div class="heading">
        <h2 class="logo"><%= link_to "MyBlogOnRailsApp", users_path %></h2>
      </div>
      <ul class="nav-ul">
        <% if user_signed_in? %>
          <li class="nav-link"><%= link_to "My posts", user_posts_path(current_user.id) %></li>
          <li class="nav-link"><%= link_to "Create a post", new_user_post_path(current_user.id) %></li>
          <li class="nav-link"><%= link_to "Account", edit_user_registration_path, class: "btn right" %></li>
          <li class="nav-link">
            <%= link_to user_path(current_user.id) do %>
              <%= current_user.name %>'s profile
            <% end %>
          </li>
          <li class="nav-link"><%= button_to("Log Out", destroy_user_session_path, method: :delete,class: "nav-link", class: "btn") %></li>
        <% else %>
          <li class="nav-link"><%= link_to "Sign in", new_user_session_path %></li>
          <li class="nav-link"><%= link_to "Sign up", new_user_registration_path %></li>

        <% end %>
      </ul>
    </div>
  </nav>
  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

    <body>
    <%= render "layouts/navbar" %>
    <% flash.each do |name, msg| -%>
      <p class="bg-green p-1"><%= msg %></p>
    <% end -%>
    <div class="container center">
      <%= yield %>
    </div>

  </body>
</html>